### ISSUE TITLE
Unable to create a repo without s3 cache

### ISSUE THREAD

**Issue by srid** [mightybyte/zeus#33]
Not sure if this was intended. When trying to create a repo, the `Add Repo` button remains **disabled**. I note that 'S3 Cache' is the only field unfilled, which is intentional on my part as I don't intend to use an *external* cache at all.

![image](https://user-images.githubusercontent.com/3998/85235709-43869e80-b3e5-11ea-9dcf-525005fe8f2a.png)

**Comment by mightybyte** [comment]
Fixed by pull request #34
